// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"shaanmei_backend/dao/model"
)

func newCarrierSeriesDatum(db *gorm.DB, opts ...gen.DOOption) carrierSeriesDatum {
	_carrierSeriesDatum := carrierSeriesDatum{}

	_carrierSeriesDatum.carrierSeriesDatumDo.UseDB(db, opts...)
	_carrierSeriesDatum.carrierSeriesDatumDo.UseModel(&model.CarrierSeriesDatum{})

	tableName := _carrierSeriesDatum.carrierSeriesDatumDo.TableName()
	_carrierSeriesDatum.ALL = field.NewAsterisk(tableName)
	_carrierSeriesDatum.ID = field.NewInt32(tableName, "id")
	_carrierSeriesDatum.CarrierName = field.NewString(tableName, "carrier_name")
	_carrierSeriesDatum.AvgShipmentPrice = field.NewFloat32(tableName, "avg_shipment_price")
	_carrierSeriesDatum.ShipmentVolume = field.NewFloat32(tableName, "shipment_volume")
	_carrierSeriesDatum.Timestamp = field.NewTime(tableName, "timestamp")

	_carrierSeriesDatum.fillFieldMap()

	return _carrierSeriesDatum
}

type carrierSeriesDatum struct {
	carrierSeriesDatumDo carrierSeriesDatumDo

	ALL              field.Asterisk
	ID               field.Int32
	CarrierName      field.String
	AvgShipmentPrice field.Float32
	ShipmentVolume   field.Float32
	Timestamp        field.Time

	fieldMap map[string]field.Expr
}

func (c carrierSeriesDatum) Table(newTableName string) *carrierSeriesDatum {
	c.carrierSeriesDatumDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c carrierSeriesDatum) As(alias string) *carrierSeriesDatum {
	c.carrierSeriesDatumDo.DO = *(c.carrierSeriesDatumDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *carrierSeriesDatum) updateTableName(table string) *carrierSeriesDatum {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt32(table, "id")
	c.CarrierName = field.NewString(table, "carrier_name")
	c.AvgShipmentPrice = field.NewFloat32(table, "avg_shipment_price")
	c.ShipmentVolume = field.NewFloat32(table, "shipment_volume")
	c.Timestamp = field.NewTime(table, "timestamp")

	c.fillFieldMap()

	return c
}

func (c *carrierSeriesDatum) WithContext(ctx context.Context) *carrierSeriesDatumDo {
	return c.carrierSeriesDatumDo.WithContext(ctx)
}

func (c carrierSeriesDatum) TableName() string { return c.carrierSeriesDatumDo.TableName() }

func (c carrierSeriesDatum) Alias() string { return c.carrierSeriesDatumDo.Alias() }

func (c carrierSeriesDatum) Columns(cols ...field.Expr) gen.Columns {
	return c.carrierSeriesDatumDo.Columns(cols...)
}

func (c *carrierSeriesDatum) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *carrierSeriesDatum) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 5)
	c.fieldMap["id"] = c.ID
	c.fieldMap["carrier_name"] = c.CarrierName
	c.fieldMap["avg_shipment_price"] = c.AvgShipmentPrice
	c.fieldMap["shipment_volume"] = c.ShipmentVolume
	c.fieldMap["timestamp"] = c.Timestamp
}

func (c carrierSeriesDatum) clone(db *gorm.DB) carrierSeriesDatum {
	c.carrierSeriesDatumDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c carrierSeriesDatum) replaceDB(db *gorm.DB) carrierSeriesDatum {
	c.carrierSeriesDatumDo.ReplaceDB(db)
	return c
}

type carrierSeriesDatumDo struct{ gen.DO }

func (c carrierSeriesDatumDo) Debug() *carrierSeriesDatumDo {
	return c.withDO(c.DO.Debug())
}

func (c carrierSeriesDatumDo) WithContext(ctx context.Context) *carrierSeriesDatumDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c carrierSeriesDatumDo) ReadDB() *carrierSeriesDatumDo {
	return c.Clauses(dbresolver.Read)
}

func (c carrierSeriesDatumDo) WriteDB() *carrierSeriesDatumDo {
	return c.Clauses(dbresolver.Write)
}

func (c carrierSeriesDatumDo) Session(config *gorm.Session) *carrierSeriesDatumDo {
	return c.withDO(c.DO.Session(config))
}

func (c carrierSeriesDatumDo) Clauses(conds ...clause.Expression) *carrierSeriesDatumDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c carrierSeriesDatumDo) Returning(value interface{}, columns ...string) *carrierSeriesDatumDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c carrierSeriesDatumDo) Not(conds ...gen.Condition) *carrierSeriesDatumDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c carrierSeriesDatumDo) Or(conds ...gen.Condition) *carrierSeriesDatumDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c carrierSeriesDatumDo) Select(conds ...field.Expr) *carrierSeriesDatumDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c carrierSeriesDatumDo) Where(conds ...gen.Condition) *carrierSeriesDatumDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c carrierSeriesDatumDo) Order(conds ...field.Expr) *carrierSeriesDatumDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c carrierSeriesDatumDo) Distinct(cols ...field.Expr) *carrierSeriesDatumDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c carrierSeriesDatumDo) Omit(cols ...field.Expr) *carrierSeriesDatumDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c carrierSeriesDatumDo) Join(table schema.Tabler, on ...field.Expr) *carrierSeriesDatumDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c carrierSeriesDatumDo) LeftJoin(table schema.Tabler, on ...field.Expr) *carrierSeriesDatumDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c carrierSeriesDatumDo) RightJoin(table schema.Tabler, on ...field.Expr) *carrierSeriesDatumDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c carrierSeriesDatumDo) Group(cols ...field.Expr) *carrierSeriesDatumDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c carrierSeriesDatumDo) Having(conds ...gen.Condition) *carrierSeriesDatumDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c carrierSeriesDatumDo) Limit(limit int) *carrierSeriesDatumDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c carrierSeriesDatumDo) Offset(offset int) *carrierSeriesDatumDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c carrierSeriesDatumDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *carrierSeriesDatumDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c carrierSeriesDatumDo) Unscoped() *carrierSeriesDatumDo {
	return c.withDO(c.DO.Unscoped())
}

func (c carrierSeriesDatumDo) Create(values ...*model.CarrierSeriesDatum) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c carrierSeriesDatumDo) CreateInBatches(values []*model.CarrierSeriesDatum, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c carrierSeriesDatumDo) Save(values ...*model.CarrierSeriesDatum) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c carrierSeriesDatumDo) First() (*model.CarrierSeriesDatum, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CarrierSeriesDatum), nil
	}
}

func (c carrierSeriesDatumDo) Take() (*model.CarrierSeriesDatum, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CarrierSeriesDatum), nil
	}
}

func (c carrierSeriesDatumDo) Last() (*model.CarrierSeriesDatum, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CarrierSeriesDatum), nil
	}
}

func (c carrierSeriesDatumDo) Find() ([]*model.CarrierSeriesDatum, error) {
	result, err := c.DO.Find()
	return result.([]*model.CarrierSeriesDatum), err
}

func (c carrierSeriesDatumDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CarrierSeriesDatum, err error) {
	buf := make([]*model.CarrierSeriesDatum, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c carrierSeriesDatumDo) FindInBatches(result *[]*model.CarrierSeriesDatum, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c carrierSeriesDatumDo) Attrs(attrs ...field.AssignExpr) *carrierSeriesDatumDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c carrierSeriesDatumDo) Assign(attrs ...field.AssignExpr) *carrierSeriesDatumDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c carrierSeriesDatumDo) Joins(fields ...field.RelationField) *carrierSeriesDatumDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c carrierSeriesDatumDo) Preload(fields ...field.RelationField) *carrierSeriesDatumDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c carrierSeriesDatumDo) FirstOrInit() (*model.CarrierSeriesDatum, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CarrierSeriesDatum), nil
	}
}

func (c carrierSeriesDatumDo) FirstOrCreate() (*model.CarrierSeriesDatum, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CarrierSeriesDatum), nil
	}
}

func (c carrierSeriesDatumDo) FindByPage(offset int, limit int) (result []*model.CarrierSeriesDatum, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c carrierSeriesDatumDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c carrierSeriesDatumDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c carrierSeriesDatumDo) Delete(models ...*model.CarrierSeriesDatum) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *carrierSeriesDatumDo) withDO(do gen.Dao) *carrierSeriesDatumDo {
	c.DO = *do.(*gen.DO)
	return c
}
