// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRouteDatum = "route_data"

// RouteDatum mapped from table <route_data>
type RouteDatum struct {
	ID                   int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RouteName            string    `gorm:"column:route_name" json:"route_name"`
	MineName             string    `gorm:"column:mine_name" json:"mine_name"`
	DestinationRegion    string    `gorm:"column:destination_region" json:"destination_region"`
	RouteDistance        float32   `gorm:"column:route_distance" json:"route_distance"`
	AvgShipmentUnitPrice float32   `gorm:"column:avg_shipment_unit_price" json:"avg_shipment_unit_price"`
	ShipmentVolume       float32   `gorm:"column:shipment_volume" json:"shipment_volume"`
	Timestamp            time.Time `gorm:"column:timestamp" json:"timestamp"`
}

// TableName RouteDatum's table name
func (*RouteDatum) TableName() string {
	return TableNameRouteDatum
}
