// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameShipmentPrice = "shipment_price"

// ShipmentPrice mapped from table <shipment_price>
type ShipmentPrice struct {
	ID                   int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OriginLongitude      float32   `gorm:"column:origin_longitude" json:"origin_longitude"`
	OriginLatitude       float32   `gorm:"column:origin_latitude" json:"origin_latitude"`
	OriginName           string    `gorm:"column:origin_name" json:"origin_name"`
	OriginProvince       string    `gorm:"column:origin_province" json:"origin_province"`
	OriginCity           string    `gorm:"column:origin_city" json:"origin_city"`
	OriginCounty         string    `gorm:"column:origin_county" json:"origin_county"`
	DestinationLongitude float32   `gorm:"column:destination_longitude" json:"destination_longitude"`
	DestinationLatitude  float32   `gorm:"column:destination_latitude" json:"destination_latitude"`
	DestinationProvince  string    `gorm:"column:destination_province" json:"destination_province"`
	DestinationCity      string    `gorm:"column:destination_city" json:"destination_city"`
	DestinationCounty    string    `gorm:"column:destination_county" json:"destination_county"`
	ShipmentUnitPrice    float32   `gorm:"column:shipment_unit_price" json:"shipment_unit_price"`
	ShipmentDistance     float32   `gorm:"column:shipment_distance" json:"shipment_distance"`
	ArrivalTime          time.Time `gorm:"column:arrival_time" json:"arrival_time"`
	ProductType          string    `gorm:"column:product_type" json:"product_type"`
	VehicleType          string    `gorm:"column:vehicle_type" json:"vehicle_type"`
	UnloadWeight         float32   `gorm:"column:unload_weight" json:"unload_weight"`
	VehicleName          string    `gorm:"column:vehicle_name" json:"vehicle_name"`
	DriverName           string    `gorm:"column:driver_name" json:"driver_name"`
	OwnerName            string    `gorm:"column:owner_name" json:"owner_name"`
	CarrierName          string    `gorm:"column:carrier_name" json:"carrier_name"`
}

// TableName ShipmentPrice's table name
func (*ShipmentPrice) TableName() string {
	return TableNameShipmentPrice
}
