// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTimeseriesDatum = "timeseries_data"

// TimeseriesDatum mapped from table <timeseries_data>
type TimeseriesDatum struct {
	ID               int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AvgShipmentPrice float32   `gorm:"column:avg_shipment_price" json:"avg_shipment_price"`
	CoalType         string    `gorm:"column:coal_type" json:"coal_type"`
	ShipmentVolume   float32   `gorm:"column:shipment_volume" json:"shipment_volume"`
	Timestamp        time.Time `gorm:"column:timestamp" json:"timestamp"`
	CarrierName      string    `gorm:"column:carrier_name" json:"carrier_name"`
	MineName         string    `gorm:"column:mine_name" json:"mine_name"`
}

// TableName TimeseriesDatum's table name
func (*TimeseriesDatum) TableName() string {
	return TableNameTimeseriesDatum
}
