// Code generated by "stringer -type ErrCode -linecomment"; DO NOT EDIT.

package errcode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServerError-10001]
	_ = x[ParamError-10002]
	_ = x[QueryDatabaseError-11001]
	_ = x[RecordNotExist-11002]
	_ = x[InsertDatabaseError-11003]
	_ = x[DeleteDatabaseError-11004]
	_ = x[UpdateDatabaseError-11005]
	_ = x[WriteRedisError-11006]
	_ = x[GetRedisError-11007]
}

const (
	_ErrCode_name_0 = "服务内部错误请求参数有误"
	_ErrCode_name_1 = "查询数据错误查询记录不存在插入数据错误删除数据错误更新数据错误写入Redis错误查询Redis错误"
)

var (
	_ErrCode_index_0 = [...]uint8{0, 18, 36}
	_ErrCode_index_1 = [...]uint8{0, 18, 39, 57, 75, 93, 110, 127}
)

func (i ErrCode) String() string {
	switch {
	case 10001 <= i && i <= 10002:
		i -= 10001
		return _ErrCode_name_0[_ErrCode_index_0[i]:_ErrCode_index_0[i+1]]
	case 11001 <= i && i <= 11007:
		i -= 11001
		return _ErrCode_name_1[_ErrCode_index_1[i]:_ErrCode_index_1[i+1]]
	default:
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
